site_name: AlphaLens
site_description: AI Financial Research Assistant
site_author: Akash

theme:
  name: material

nav:
  - Home: index.md
  - Architecture: architecture.md
  - Database: database.md
  - Folder Structure: folder_structure.md
  - Modules: modules.md
  - API: api.md
  - Roadmap: roadmap.md

markdown_extensions:
  - admonition
  - tables
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences