site_name: AlphaLens
site_description: AI Financial Research Assistant
site_author: Akash

theme:
  name: material

nav:
  - API: api_reference.md
  - Roadmap: system_and_roadmap.md

markdown_extensions:
  - admonition
  - tables
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences