from sqlalchemy.orm import Session

from backend.repositories.market_recommendation_repository import (
    get_latest_market_recommendation,
)


class RecommendationContextRetriever:
    """
    Retrieve the latest company market recommendation
    generated by Module 10.

    This service does not generate a new recommendation.
    It only exposes the latest stored recommendation
    to Company Chat.
    """

    def retrieve(
        self,
        db: Session,
        company_id: int,
    ) -> dict | None:

        recommendation = (
            get_latest_market_recommendation(
                db=db,
                company_id=company_id,
            )
        )

        if recommendation is None:
            return None

        return {
            "id": recommendation.id,
            "recommendation": (
                recommendation.recommendation
            ),
            "score": recommendation.score,
            "confidence": recommendation.confidence,
            "financial_score": (
                recommendation.financial_score
            ),
            "sentiment_score": (
                recommendation.sentiment_score
            ),
            "financial_reasoning": (
                recommendation.financial_reasoning
            ),
            "sentiment_reasoning": (
                recommendation.sentiment_reasoning
            ),
            "overall_reasoning": (
                recommendation.overall_reasoning
            ),
            "confidence_reasoning": (
                recommendation.confidence_reasoning
            ),
            "model_version": (
                recommendation.model_version
            ),
            "created_at": (
                recommendation.created_at
            ),
        }


recommendation_context_retriever = (
    RecommendationContextRetriever()
)