"""
Curated Default Market Universe and High-Fidelity Seed / Fallback Dataset.
Ensures the Home Page and Market Overview APIs always have comprehensive,
realistic data even if external market APIs are unavailable or database is unseeded.
"""

from datetime import datetime, timezone, timedelta

def now_utc():
    return datetime.now(timezone.utc)

today = now_utc()

DEFAULT_INDICES = [
    {
        "symbol": "^NSEI",
        "name": "NIFTY 50",
        "category": "benchmark",
        "current_value": 25145.75,
        "change": 142.30,
        "percent_change": 0.57,
        "open_value": 25010.50,
        "high_value": 25180.20,
        "low_value": 24985.40,
        "previous_close": 25003.45,
    },
    {
        "symbol": "^BSESN",
        "name": "SENSEX",
        "category": "benchmark",
        "current_value": 82215.10,
        "change": 455.80,
        "percent_change": 0.56,
        "open_value": 81820.00,
        "high_value": 82340.60,
        "low_value": 81750.25,
        "previous_close": 81759.30,
    },
    {
        "symbol": "^NSEBANK",
        "name": "NIFTY BANK",
        "category": "sectoral",
        "current_value": 52190.40,
        "change": 380.25,
        "percent_change": 0.73,
        "open_value": 51880.00,
        "high_value": 52310.00,
        "low_value": 51800.50,
        "previous_close": 51810.15,
    },
    {
        "symbol": "^CNXIT",
        "name": "NIFTY IT",
        "category": "sectoral",
        "current_value": 41850.60,
        "change": -125.40,
        "percent_change": -0.30,
        "open_value": 42020.10,
        "high_value": 42150.00,
        "low_value": 41720.00,
        "previous_close": 41976.00,
    },
    {
        "symbol": "^GSPC",
        "name": "S&P 500",
        "category": "global",
        "current_value": 5738.17,
        "change": 24.50,
        "percent_change": 0.43,
        "open_value": 5715.00,
        "high_value": 5750.12,
        "low_value": 5708.40,
        "previous_close": 5713.67,
    },
]


DEFAULT_STOCKS = [
    # ----------------- LARGE CAP (HIGH CAP) -----------------
    {
        "symbol": "RELIANCE",
        "company_name": "Reliance Industries Ltd",
        "sector": "Energy & Oil",
        "market_cap_category": "large",
        "current_price": 2985.50,
        "change": 45.20,
        "percent_change": 1.54,
        "open_price": 2945.00,
        "high_price": 2998.00,
        "low_price": 2940.00,
        "previous_close": 2940.30,
        "volume": 6850400,
        "avg_volume_10d": 5200000,
        "volume_surge_ratio": 1.32,
        "high_52w": 3024.90,
        "low_52w": 2220.30,
        "pe_ratio": 28.4,
        "market_cap": 2020000.0,
    },
    {
        "symbol": "TCS",
        "company_name": "Tata Consultancy Services Ltd",
        "sector": "Technology",
        "market_cap_category": "large",
        "current_price": 4310.25,
        "change": -22.50,
        "percent_change": -0.52,
        "open_price": 4340.00,
        "high_price": 4365.00,
        "low_price": 4295.10,
        "previous_close": 4332.75,
        "volume": 2150300,
        "avg_volume_10d": 2300000,
        "volume_surge_ratio": 0.93,
        "high_52w": 4592.25,
        "low_52w": 3313.00,
        "pe_ratio": 32.1,
        "market_cap": 1560000.0,
    },
    {
        "symbol": "HDFCBANK",
        "company_name": "HDFC Bank Ltd",
        "sector": "Financial Services",
        "market_cap_category": "large",
        "current_price": 1698.80,
        "change": 28.40,
        "percent_change": 1.70,
        "open_price": 1675.00,
        "high_price": 1705.00,
        "low_price": 1670.20,
        "previous_close": 1670.40,
        "volume": 12840000,
        "avg_volume_10d": 9800000,
        "volume_surge_ratio": 1.31,
        "high_52w": 1794.00,
        "low_52w": 1363.55,
        "pe_ratio": 19.8,
        "market_cap": 1290000.0,
    },
    {
        "symbol": "INFY",
        "company_name": "Infosys Ltd",
        "sector": "Technology",
        "market_cap_category": "large",
        "current_price": 1925.10,
        "change": -18.70,
        "percent_change": -0.96,
        "open_price": 1950.00,
        "high_price": 1962.00,
        "low_price": 1918.00,
        "previous_close": 1943.80,
        "volume": 4920000,
        "avg_volume_10d": 5100000,
        "volume_surge_ratio": 0.96,
        "high_52w": 1991.45,
        "low_52w": 1358.35,
        "pe_ratio": 29.5,
        "market_cap": 800000.0,
    },
    {
        "symbol": "ICICIBANK",
        "company_name": "ICICI Bank Ltd",
        "sector": "Financial Services",
        "market_cap_category": "large",
        "current_price": 1285.40,
        "change": 24.10,
        "percent_change": 1.91,
        "open_price": 1265.00,
        "high_price": 1292.00,
        "low_price": 1262.10,
        "previous_close": 1261.30,
        "volume": 9450000,
        "avg_volume_10d": 8100000,
        "volume_surge_ratio": 1.17,
        "high_52w": 1300.00,
        "low_52w": 910.50,
        "pe_ratio": 18.2,
        "market_cap": 905000.0,
    },
    {
        "symbol": "BHARTIARTL",
        "company_name": "Bharti Airtel Ltd",
        "sector": "Telecommunication",
        "market_cap_category": "large",
        "current_price": 1675.20,
        "change": 38.60,
        "percent_change": 2.36,
        "open_price": 1640.00,
        "high_price": 1682.00,
        "low_price": 1638.00,
        "previous_close": 1636.60,
        "volume": 5890000,
        "avg_volume_10d": 4200000,
        "volume_surge_ratio": 1.40,
        "high_52w": 1690.00,
        "low_52w": 890.10,
        "pe_ratio": 42.6,
        "market_cap": 970000.0,
    },
    {
        "symbol": "ITC",
        "company_name": "ITC Ltd",
        "sector": "Consumer Goods",
        "market_cap_category": "large",
        "current_price": 508.40,
        "change": -4.20,
        "percent_change": -0.82,
        "open_price": 514.00,
        "high_price": 516.50,
        "low_price": 506.00,
        "previous_close": 512.60,
        "volume": 7650000,
        "avg_volume_10d": 8500000,
        "volume_surge_ratio": 0.90,
        "high_52w": 528.50,
        "low_52w": 399.30,
        "pe_ratio": 30.5,
        "market_cap": 635000.0,
    },
    {
        "symbol": "LT",
        "company_name": "Larsen & Toubro Ltd",
        "sector": "Infrastructure",
        "market_cap_category": "large",
        "current_price": 3810.00,
        "change": 72.50,
        "percent_change": 1.94,
        "open_price": 3750.00,
        "high_price": 3828.00,
        "low_price": 3740.00,
        "previous_close": 3737.50,
        "volume": 2480000,
        "avg_volume_10d": 1900000,
        "volume_surge_ratio": 1.31,
        "high_52w": 3919.90,
        "low_52w": 2872.20,
        "pe_ratio": 35.8,
        "market_cap": 524000.0,
    },
    {
        "symbol": "SBIN",
        "company_name": "State Bank of India",
        "sector": "Financial Services",
        "market_cap_category": "large",
        "current_price": 815.75,
        "change": 11.25,
        "percent_change": 1.40,
        "open_price": 807.00,
        "high_price": 820.00,
        "low_price": 805.20,
        "previous_close": 804.50,
        "volume": 14200000,
        "avg_volume_10d": 12500000,
        "volume_surge_ratio": 1.14,
        "high_52w": 912.00,
        "low_52w": 555.25,
        "pe_ratio": 10.4,
        "market_cap": 728000.0,
    },
    {
        "symbol": "TATAMOTORS",
        "company_name": "Tata Motors Ltd",
        "sector": "Automobile",
        "market_cap_category": "large",
        "current_price": 995.10,
        "change": -16.40,
        "percent_change": -1.62,
        "open_price": 1014.00,
        "high_price": 1018.50,
        "low_price": 990.20,
        "previous_close": 1011.50,
        "volume": 8450000,
        "avg_volume_10d": 7200000,
        "volume_surge_ratio": 1.17,
        "high_52w": 1179.05,
        "low_52w": 605.00,
        "pe_ratio": 11.2,
        "market_cap": 365000.0,
    },
    {
        "symbol": "SUNPHARMA",
        "company_name": "Sun Pharmaceutical Industries Ltd",
        "sector": "Healthcare",
        "market_cap_category": "large",
        "current_price": 1895.00,
        "change": 32.50,
        "percent_change": 1.74,
        "open_price": 1868.00,
        "high_price": 1908.00,
        "low_price": 1865.00,
        "previous_close": 1862.50,
        "volume": 3210000,
        "avg_volume_10d": 2400000,
        "volume_surge_ratio": 1.34,
        "high_52w": 1935.00,
        "low_52w": 1095.00,
        "pe_ratio": 38.4,
        "market_cap": 454000.0,
    },
    {
        "symbol": "HINDUNILVR",
        "company_name": "Hindustan Unilever Ltd",
        "sector": "Consumer Goods",
        "market_cap_category": "large",
        "current_price": 2845.00,
        "change": -25.00,
        "percent_change": -0.87,
        "open_price": 2875.00,
        "high_price": 2888.00,
        "low_price": 2838.00,
        "previous_close": 2870.00,
        "volume": 1850000,
        "avg_volume_10d": 1950000,
        "volume_surge_ratio": 0.95,
        "high_52w": 3035.00,
        "low_52w": 2172.05,
        "pe_ratio": 62.1,
        "market_cap": 668000.0,
    },

    # ----------------- MID CAP -----------------
    {
        "symbol": "TRENT",
        "company_name": "Trent Ltd",
        "sector": "Consumer Goods",
        "market_cap_category": "mid",
        "current_price": 7520.00,
        "change": 245.00,
        "percent_change": 3.37,
        "open_price": 7320.00,
        "high_price": 7590.00,
        "low_price": 7305.00,
        "previous_close": 7275.00,
        "volume": 1920000,
        "avg_volume_10d": 950000,
        "volume_surge_ratio": 2.02,
        "high_52w": 7650.00,
        "low_52w": 2012.00,
        "pe_ratio": 115.0,
        "market_cap": 267000.0,
    },
    {
        "symbol": "POLYCAB",
        "company_name": "Polycab India Ltd",
        "sector": "Capital Goods",
        "market_cap_category": "mid",
        "current_price": 6840.00,
        "change": 168.00,
        "percent_change": 2.52,
        "open_price": 6690.00,
        "high_price": 6890.00,
        "low_price": 6680.00,
        "previous_close": 6672.00,
        "volume": 840000,
        "avg_volume_10d": 520000,
        "volume_surge_ratio": 1.62,
        "high_52w": 7200.00,
        "low_52w": 4625.00,
        "pe_ratio": 54.2,
        "market_cap": 102000.0,
    },
    {
        "symbol": "PERSISTENT",
        "company_name": "Persistent Systems Ltd",
        "sector": "Technology",
        "market_cap_category": "mid",
        "current_price": 5410.00,
        "change": -84.00,
        "percent_change": -1.53,
        "open_price": 5510.00,
        "high_price": 5545.00,
        "low_price": 5390.00,
        "previous_close": 5494.00,
        "volume": 620000,
        "avg_volume_10d": 650000,
        "volume_surge_ratio": 0.95,
        "high_52w": 5700.00,
        "low_52w": 3300.00,
        "pe_ratio": 62.4,
        "market_cap": 83000.0,
    },
    {
        "symbol": "COFORGE",
        "company_name": "Coforge Ltd",
        "sector": "Technology",
        "market_cap_category": "mid",
        "current_price": 7280.00,
        "change": -140.00,
        "percent_change": -1.89,
        "open_price": 7450.00,
        "high_price": 7490.00,
        "low_price": 7240.00,
        "previous_close": 7420.00,
        "volume": 780000,
        "avg_volume_10d": 690000,
        "volume_surge_ratio": 1.13,
        "high_52w": 7750.00,
        "low_52w": 4450.00,
        "pe_ratio": 52.8,
        "market_cap": 48500.0,
    },
    {
        "symbol": "TATAPOWER",
        "company_name": "Tata Power Company Ltd",
        "sector": "Energy & Oil",
        "market_cap_category": "mid",
        "current_price": 458.20,
        "change": 14.80,
        "percent_change": 3.34,
        "open_price": 445.00,
        "high_price": 462.50,
        "low_price": 444.00,
        "previous_close": 443.40,
        "volume": 12500000,
        "avg_volume_10d": 7800000,
        "volume_surge_ratio": 1.60,
        "high_52w": 475.00,
        "low_52w": 252.00,
        "pe_ratio": 38.6,
        "market_cap": 146000.0,
    },
    {
        "symbol": "ASHOKLEY",
        "company_name": "Ashok Leyland Ltd",
        "sector": "Automobile",
        "market_cap_category": "mid",
        "current_price": 238.40,
        "change": 6.80,
        "percent_change": 2.94,
        "open_price": 232.00,
        "high_price": 240.50,
        "low_price": 231.50,
        "previous_close": 231.60,
        "volume": 9800000,
        "avg_volume_10d": 6100000,
        "volume_surge_ratio": 1.61,
        "high_52w": 245.00,
        "low_52w": 165.00,
        "pe_ratio": 24.3,
        "market_cap": 70000.0,
    },
    {
        "symbol": "FEDERALBNK",
        "company_name": "Federal Bank Ltd",
        "sector": "Financial Services",
        "market_cap_category": "mid",
        "current_price": 194.50,
        "change": 3.20,
        "percent_change": 1.67,
        "open_price": 191.50,
        "high_price": 196.00,
        "low_price": 191.00,
        "previous_close": 191.30,
        "volume": 11200000,
        "avg_volume_10d": 8900000,
        "volume_surge_ratio": 1.26,
        "high_52w": 208.00,
        "low_52w": 138.00,
        "pe_ratio": 11.9,
        "market_cap": 47500.0,
    },
    {
        "symbol": "MAXHEALTH",
        "company_name": "Max Healthcare Institute Ltd",
        "sector": "Healthcare",
        "market_cap_category": "mid",
        "current_price": 945.00,
        "change": 22.00,
        "percent_change": 2.38,
        "open_price": 925.00,
        "high_price": 952.00,
        "low_price": 922.00,
        "previous_close": 923.00,
        "volume": 2400000,
        "avg_volume_10d": 1700000,
        "volume_surge_ratio": 1.41,
        "high_52w": 965.00,
        "low_52w": 550.00,
        "pe_ratio": 72.4,
        "market_cap": 91800.0,
    },
    {
        "symbol": "JUBLFOOD",
        "company_name": "Jubilant FoodWorks Ltd",
        "sector": "Consumer Goods",
        "market_cap_category": "mid",
        "current_price": 632.10,
        "change": -14.30,
        "percent_change": -2.21,
        "open_price": 648.00,
        "high_price": 651.00,
        "low_price": 628.00,
        "previous_close": 646.40,
        "volume": 3100000,
        "avg_volume_10d": 2600000,
        "volume_surge_ratio": 1.19,
        "high_52w": 715.00,
        "low_52w": 420.00,
        "pe_ratio": 84.1,
        "market_cap": 41700.0,
    },
    {
        "symbol": "DIXON",
        "company_name": "Dixon Technologies Ltd",
        "sector": "Capital Goods",
        "market_cap_category": "mid",
        "current_price": 13950.00,
        "change": 480.00,
        "percent_change": 3.56,
        "open_price": 13500.00,
        "high_price": 14100.00,
        "low_price": 13480.00,
        "previous_close": 13470.00,
        "volume": 680000,
        "avg_volume_10d": 340000,
        "volume_surge_ratio": 2.00,
        "high_52w": 14250.00,
        "low_52w": 4700.00,
        "pe_ratio": 128.0,
        "market_cap": 83500.0,
    },

    # ----------------- SMALL CAP -----------------
    {
        "symbol": "KAYNES",
        "company_name": "Kaynes Technology India Ltd",
        "sector": "Capital Goods",
        "market_cap_category": "small",
        "current_price": 5420.00,
        "change": 260.00,
        "percent_change": 5.04,
        "open_price": 5180.00,
        "high_price": 5510.00,
        "low_price": 5160.00,
        "previous_close": 5160.00,
        "volume": 720000,
        "avg_volume_10d": 310000,
        "volume_surge_ratio": 2.32,
        "high_52w": 5600.00,
        "low_52w": 2150.00,
        "pe_ratio": 94.0,
        "market_cap": 34500.0,
    },
    {
        "symbol": "HAPPSTMNDS",
        "company_name": "Happiest Minds Technologies Ltd",
        "sector": "Technology",
        "market_cap_category": "small",
        "current_price": 768.00,
        "change": -24.50,
        "percent_change": -3.09,
        "open_price": 794.00,
        "high_price": 798.00,
        "low_price": 762.00,
        "previous_close": 792.50,
        "volume": 1250000,
        "avg_volume_10d": 880000,
        "volume_surge_ratio": 1.42,
        "high_52w": 940.00,
        "low_52w": 735.00,
        "pe_ratio": 45.2,
        "market_cap": 11700.0,
    },
    {
        "symbol": "SONACOMS",
        "company_name": "Sona BLW Precision Forgings Ltd",
        "sector": "Automobile",
        "market_cap_category": "small",
        "current_price": 725.00,
        "change": 28.50,
        "percent_change": 4.09,
        "open_price": 698.00,
        "high_price": 732.00,
        "low_price": 695.00,
        "previous_close": 696.50,
        "volume": 2840000,
        "avg_volume_10d": 1450000,
        "volume_surge_ratio": 1.96,
        "high_52w": 750.00,
        "low_52w": 510.00,
        "pe_ratio": 78.5,
        "market_cap": 42500.0,
    },
    {
        "symbol": "KPITTECH",
        "company_name": "KPIT Technologies Ltd",
        "sector": "Technology",
        "market_cap_category": "small",
        "current_price": 1740.00,
        "change": 58.00,
        "percent_change": 3.45,
        "open_price": 1690.00,
        "high_price": 1760.00,
        "low_price": 1685.00,
        "previous_close": 1682.00,
        "volume": 2100000,
        "avg_volume_10d": 1300000,
        "volume_surge_ratio": 1.62,
        "high_52w": 1928.00,
        "low_52w": 1110.00,
        "pe_ratio": 68.2,
        "market_cap": 47600.0,
    },
    {
        "symbol": "CDSL",
        "company_name": "Central Depository Services India Ltd",
        "sector": "Financial Services",
        "market_cap_category": "small",
        "current_price": 1585.00,
        "change": 62.00,
        "percent_change": 4.07,
        "open_price": 1530.00,
        "high_price": 1605.00,
        "low_price": 1525.00,
        "previous_close": 1523.00,
        "volume": 3400000,
        "avg_volume_10d": 1900000,
        "volume_surge_ratio": 1.79,
        "high_52w": 1695.00,
        "low_52w": 850.00,
        "pe_ratio": 58.9,
        "market_cap": 33100.0,
    },
    {
        "symbol": "CAMS",
        "company_name": "Computer Age Management Services Ltd",
        "sector": "Financial Services",
        "market_cap_category": "small",
        "current_price": 4680.00,
        "change": -95.00,
        "percent_change": -1.99,
        "open_price": 4780.00,
        "high_price": 4810.00,
        "low_price": 4650.00,
        "previous_close": 4775.00,
        "volume": 410000,
        "avg_volume_10d": 380000,
        "volume_surge_ratio": 1.08,
        "high_52w": 4920.00,
        "low_52w": 2300.00,
        "pe_ratio": 54.0,
        "market_cap": 23000.0,
    },
    {
        "symbol": "ROUTE",
        "company_name": "Route Mobile Ltd",
        "sector": "Telecommunication",
        "market_cap_category": "small",
        "current_price": 1560.00,
        "change": -42.00,
        "percent_change": -2.62,
        "open_price": 1605.00,
        "high_price": 1610.00,
        "low_price": 1545.00,
        "previous_close": 1602.00,
        "volume": 480000,
        "avg_volume_10d": 350000,
        "volume_surge_ratio": 1.37,
        "high_52w": 1780.00,
        "low_52w": 1420.00,
        "pe_ratio": 29.5,
        "market_cap": 9800.0,
    },
    {
        "symbol": "KNRCON",
        "company_name": "KNR Constructions Ltd",
        "sector": "Infrastructure",
        "market_cap_category": "small",
        "current_price": 348.00,
        "change": 12.50,
        "percent_change": 3.73,
        "open_price": 338.00,
        "high_price": 352.00,
        "low_price": 336.00,
        "previous_close": 335.50,
        "volume": 2100000,
        "avg_volume_10d": 1200000,
        "volume_surge_ratio": 1.75,
        "high_52w": 415.00,
        "low_52w": 240.00,
        "pe_ratio": 14.8,
        "market_cap": 9800.0,
    },
    {
        "symbol": "NEULANDLAB",
        "company_name": "Neuland Laboratories Ltd",
        "sector": "Healthcare",
        "market_cap_category": "small",
        "current_price": 14250.00,
        "change": -310.00,
        "percent_change": -2.13,
        "open_price": 14600.00,
        "high_price": 14750.00,
        "low_price": 14120.00,
        "previous_close": 14560.00,
        "volume": 120000,
        "avg_volume_10d": 95000,
        "volume_surge_ratio": 1.26,
        "high_52w": 15800.00,
        "low_52w": 4600.00,
        "pe_ratio": 58.2,
        "market_cap": 18300.0,
    },
    {
        "symbol": "ELECON",
        "company_name": "Elecon Engineering Company Ltd",
        "sector": "Capital Goods",
        "market_cap_category": "small",
        "current_price": 635.00,
        "change": 34.00,
        "percent_change": 5.66,
        "open_price": 605.00,
        "high_price": 645.00,
        "low_price": 602.00,
        "previous_close": 601.00,
        "volume": 2900000,
        "avg_volume_10d": 1100000,
        "volume_surge_ratio": 2.64,
        "high_52w": 710.00,
        "low_52w": 390.00,
        "pe_ratio": 36.4,
        "market_cap": 14200.0,
    },
]


DEFAULT_QUARTERLY_RESULTS = [
    # Recent Declared Results
    {
        "symbol": "TCS",
        "company_name": "Tata Consultancy Services Ltd",
        "sector": "Technology",
        "fiscal_year": "FY25",
        "quarter": "Q1",
        "result_date": today - timedelta(days=22),
        "is_upcoming": False,
        "revenue": 62613.0,
        "revenue_growth_yoy": 5.4,
        "net_profit": 12040.0,
        "profit_growth_yoy": 8.7,
        "verdict": "Beat",
        "impact_percent": 2.8,
        "key_highlights": "Operating margin expanded to 26.0%; strong growth in North America BFSI and manufacturing deal wins totaling $8.3B TCV.",
    },
    {
        "symbol": "INFY",
        "company_name": "Infosys Ltd",
        "sector": "Technology",
        "fiscal_year": "FY25",
        "quarter": "Q1",
        "result_date": today - timedelta(days=18),
        "is_upcoming": False,
        "revenue": 39315.0,
        "revenue_growth_yoy": 3.6,
        "net_profit": 6368.0,
        "profit_growth_yoy": 7.1,
        "verdict": "Beat",
        "impact_percent": 3.4,
        "key_highlights": "Raised full-year revenue growth guidance to 3-4%; large deal wins hit $4.1B.",
    },
    {
        "symbol": "HDFCBANK",
        "company_name": "HDFC Bank Ltd",
        "sector": "Financial Services",
        "fiscal_year": "FY25",
        "quarter": "Q1",
        "result_date": today - timedelta(days=15),
        "is_upcoming": False,
        "revenue": 83700.0,
        "revenue_growth_yoy": 44.8,
        "net_profit": 16175.0,
        "profit_growth_yoy": 35.3,
        "verdict": "Met",
        "impact_percent": 0.8,
        "key_highlights": "Post-merger loan growth balanced with deposit mobilization; gross NPA stable at 1.33%.",
    },
    {
        "symbol": "RELIANCE",
        "company_name": "Reliance Industries Ltd",
        "sector": "Energy & Oil",
        "fiscal_year": "FY25",
        "quarter": "Q1",
        "result_date": today - timedelta(days=12),
        "is_upcoming": False,
        "revenue": 236217.0,
        "revenue_growth_yoy": 11.5,
        "net_profit": 15138.0,
        "profit_growth_yoy": -5.5,
        "verdict": "Miss",
        "impact_percent": -1.8,
        "key_highlights": "Robust retail and telecom EBITDA offset by subdued O2C refining margins globally.",
    },
    {
        "symbol": "ICICIBANK",
        "company_name": "ICICI Bank Ltd",
        "sector": "Financial Services",
        "fiscal_year": "FY25",
        "quarter": "Q1",
        "result_date": today - timedelta(days=10),
        "is_upcoming": False,
        "revenue": 45400.0,
        "revenue_growth_yoy": 17.2,
        "net_profit": 11059.0,
        "profit_growth_yoy": 14.6,
        "verdict": "Beat",
        "impact_percent": 2.1,
        "key_highlights": "Net interest margin robust at 4.36%; domestic loan portfolio grew 15.9% YoY.",
    },
    {
        "symbol": "TRENT",
        "company_name": "Trent Ltd",
        "sector": "Consumer Goods",
        "fiscal_year": "FY25",
        "quarter": "Q1",
        "result_date": today - timedelta(days=8),
        "is_upcoming": False,
        "revenue": 4104.0,
        "revenue_growth_yoy": 56.1,
        "net_profit": 391.0,
        "profit_growth_yoy": 134.1,
        "verdict": "Beat",
        "impact_percent": 8.5,
        "key_highlights": "Blockbuster revenue growth driven by aggressive Zudio store rollout and strong same-store sales growth.",
    },
    {
        "symbol": "POLYCAB",
        "company_name": "Polycab India Ltd",
        "sector": "Capital Goods",
        "fiscal_year": "FY25",
        "quarter": "Q1",
        "result_date": today - timedelta(days=6),
        "is_upcoming": False,
        "revenue": 4698.0,
        "revenue_growth_yoy": 20.8,
        "net_profit": 401.0,
        "profit_growth_yoy": 0.6,
        "verdict": "Met",
        "impact_percent": 1.2,
        "key_highlights": "Wires & cables volume growth up 27%; operating margins healthy despite copper volatility.",
    },
    {
        "symbol": "TATAMOTORS",
        "company_name": "Tata Motors Ltd",
        "sector": "Automobile",
        "fiscal_year": "FY25",
        "quarter": "Q1",
        "result_date": today - timedelta(days=4),
        "is_upcoming": False,
        "revenue": 108048.0,
        "revenue_growth_yoy": 5.7,
        "net_profit": 5566.0,
        "profit_growth_yoy": 73.8,
        "verdict": "Beat",
        "impact_percent": 3.1,
        "key_highlights": "JLR EBIT margin reached 8.9%; net debt reduced significantly to reach zero net debt trajectory.",
    },

    # Upcoming Results
    {
        "symbol": "BHARTIARTL",
        "company_name": "Bharti Airtel Ltd",
        "sector": "Telecommunication",
        "fiscal_year": "FY25",
        "quarter": "Q2",
        "result_date": today + timedelta(days=3),
        "is_upcoming": True,
        "revenue": None,
        "revenue_growth_yoy": None,
        "net_profit": None,
        "profit_growth_yoy": None,
        "verdict": "Pending",
        "impact_percent": None,
        "key_highlights": "Street expects 12% revenue growth on recent tariff hike flow-through and ARPU expansion past Rs 215.",
    },
    {
        "symbol": "LT",
        "company_name": "Larsen & Toubro Ltd",
        "sector": "Infrastructure",
        "fiscal_year": "FY25",
        "quarter": "Q2",
        "result_date": today + timedelta(days=5),
        "is_upcoming": True,
        "revenue": None,
        "revenue_growth_yoy": None,
        "net_profit": None,
        "profit_growth_yoy": None,
        "verdict": "Pending",
        "impact_percent": None,
        "key_highlights": "Order inflows from Middle East hydrocarbon and infrastructure projects under focus; order book exceeds Rs 4.7 lakh Cr.",
    },
    {
        "symbol": "SBIN",
        "company_name": "State Bank of India",
        "sector": "Financial Services",
        "fiscal_year": "FY25",
        "quarter": "Q2",
        "result_date": today + timedelta(days=8),
        "is_upcoming": True,
        "revenue": None,
        "revenue_growth_yoy": None,
        "net_profit": None,
        "profit_growth_yoy": None,
        "verdict": "Pending",
        "impact_percent": None,
        "key_highlights": "Analysts anticipate net profit above Rs 17,000 Cr supported by sustained credit demand and lower slippages.",
    },
    {
        "symbol": "SUNPHARMA",
        "company_name": "Sun Pharmaceutical Industries Ltd",
        "sector": "Healthcare",
        "fiscal_year": "FY25",
        "quarter": "Q2",
        "result_date": today + timedelta(days=11),
        "is_upcoming": True,
        "revenue": None,
        "revenue_growth_yoy": None,
        "net_profit": None,
        "profit_growth_yoy": None,
        "verdict": "Pending",
        "impact_percent": None,
        "key_highlights": "Global specialty sales trajectory and US FDA inspection updates are primary focal points for investors.",
    },
    {
        "symbol": "DIXON",
        "company_name": "Dixon Technologies Ltd",
        "sector": "Capital Goods",
        "fiscal_year": "FY25",
        "quarter": "Q2",
        "result_date": today + timedelta(days=14),
        "is_upcoming": True,
        "revenue": None,
        "revenue_growth_yoy": None,
        "net_profit": None,
        "profit_growth_yoy": None,
        "verdict": "Pending",
        "impact_percent": None,
        "key_highlights": "Smartphone export volumes under PLI scheme expected to drive significant top-line expansion.",
    },
    {
        "symbol": "KAYNES",
        "company_name": "Kaynes Technology India Ltd",
        "sector": "Capital Goods",
        "fiscal_year": "FY25",
        "quarter": "Q2",
        "result_date": today + timedelta(days=17),
        "is_upcoming": True,
        "revenue": None,
        "revenue_growth_yoy": None,
        "net_profit": None,
        "profit_growth_yoy": None,
        "verdict": "Pending",
        "impact_percent": None,
        "key_highlights": "OSAT semiconductor packaging facility milestones and aerospace/defense electronics order updates awaited.",
    },
]


DEFAULT_IPOS = [
    # ---- Upcoming Mainboard IPOs ----
    {
        "company_name": "Hexaware Technologies Ltd",
        "symbol": "HEXAWARE",
        "exchange": "mainboard",
        "issue_date": today + timedelta(days=5),
        "price_range_low": 674.0,
        "price_range_high": 708.0,
        "total_shares": 60368544,
        "listing_price": None,
        "underwriters": "Kotak Mahindra Capital, Citigroup, JP Morgan, IIFL Securities",
        "status": "upcoming",
    },
    {
        "company_name": "Ather Energy Ltd",
        "symbol": "ATHERENRG",
        "exchange": "mainboard",
        "issue_date": today + timedelta(days=10),
        "price_range_low": 304.0,
        "price_range_high": 321.0,
        "total_shares": 80900000,
        "listing_price": None,
        "underwriters": "Axis Capital, JM Financial, Goldman Sachs",
        "status": "upcoming",
    },
    {
        "company_name": "Swiggy Ltd",
        "symbol": "SWIGGY",
        "exchange": "mainboard",
        "issue_date": today + timedelta(days=18),
        "price_range_low": 371.0,
        "price_range_high": 390.0,
        "total_shares": 115085715,
        "listing_price": None,
        "underwriters": "Kotak Mahindra Capital, Bank of America, Jefferies",
        "status": "upcoming",
    },

    # ---- Upcoming SME IPOs ----
    {
        "company_name": "Diffusion Engineers Ltd",
        "symbol": "DIFFUSENG",
        "exchange": "sme",
        "issue_date": today + timedelta(days=3),
        "price_range_low": 159.0,
        "price_range_high": 168.0,
        "total_shares": 5700000,
        "listing_price": None,
        "underwriters": "Hem Securities",
        "status": "upcoming",
    },
    {
        "company_name": "Paramount Dye Tec Ltd",
        "symbol": "PARAMNTDYE",
        "exchange": "sme",
        "issue_date": today + timedelta(days=7),
        "price_range_low": 75.0,
        "price_range_high": 79.0,
        "total_shares": 4200000,
        "listing_price": None,
        "underwriters": "SMC Capitals",
        "status": "upcoming",
    },

    # ---- Recently Listed (Mainboard) ----
    {
        "company_name": "Bajaj Housing Finance Ltd",
        "symbol": "BAJAJHFL",
        "exchange": "mainboard",
        "issue_date": today - timedelta(days=12),
        "price_range_low": 66.0,
        "price_range_high": 70.0,
        "total_shares": 937142857,
        "listing_price": 150.0,
        "underwriters": "Kotak Mahindra Capital, BofA Securities, SBI Capital",
        "status": "listed",
    },
    {
        "company_name": "Manba Finance Ltd",
        "symbol": "MANBA",
        "exchange": "mainboard",
        "issue_date": today - timedelta(days=20),
        "price_range_low": 114.0,
        "price_range_high": 120.0,
        "total_shares": 12600000,
        "listing_price": 180.0,
        "underwriters": "Unistone Capital",
        "status": "listed",
    },
    {
        "company_name": "Northern Arc Capital Ltd",
        "symbol": "NORTHARC",
        "exchange": "mainboard",
        "issue_date": today - timedelta(days=25),
        "price_range_low": 249.0,
        "price_range_high": 263.0,
        "total_shares": 19461218,
        "listing_price": 350.0,
        "underwriters": "ICICI Securities, Nomura, JM Financial",
        "status": "listed",
    },

    # ---- Recently Listed (SME) ----
    {
        "company_name": "Shree Tirupati Balajee Agro Trading Ltd",
        "symbol": "STBAGRO",
        "exchange": "sme",
        "issue_date": today - timedelta(days=8),
        "price_range_low": 78.0,
        "price_range_high": 83.0,
        "total_shares": 3800000,
        "listing_price": 118.0,
        "underwriters": "Expert Global Consultants",
        "status": "listed",
    },
]


DEFAULT_WATCHLIST_SYMBOLS = [
    "RELIANCE",
    "TCS",
    "HDFCBANK",
    "INFY",
    "ICICIBANK",
    "BHARTIARTL",
    "ITC",
    "LT",
    "SBIN",
    "TATAMOTORS",
]
